import * as fs from 'fs'

import {parseArguments} from './internal/parse-arguments'
import {readExcelFile} from './internal/excel'
import {NodeData, EdgeData, GraphData} from './internal/graph-data'

const main = async (): Promise<void> => {
  const args = parseArguments()
  const nodes: NodeData[] = []
  const edges: EdgeData[] = []

  const report = await readExcelFile(args.filename)

  report.sheets.forEach(sheet => {
    const edgeLabel = sheet.name

    const headers = sheet.data[0]

    sheet.data.slice(1).forEach(row => {
      const rowNodes: NodeData[] = row.map((cell, i) => {
        return {
          type: headers[i].value.toString(),
          label: cell.value.toString(),
        }
      })

      // Add nodes.
      rowNodes.forEach(node => {
        // Add nodes if they aren't there already.
        if (!nodes.some(({label}) => label === node.label)) {
          nodes.push(node)
        }
      })

      // Add edges.
      edges.push({
        label: edgeLabel,
        from: rowNodes[0].label,
        to: rowNodes[1].label,
      })
    })
  })

  const data: GraphData = {nodes, edges}

  // Turn the data into almost-JSON.
  // Quotes that aren't needed are removed.
  // Double quote strings are turned into single quote strings.
  // Trailing commas are added.
  const jsString = JSON.stringify(data, null, 2)
    .replace(
      /^[\t ]*"[^:\n\r]+(?<!\\)":/gm,
      match => match.replace(/"/g, ''),
    )
    // Replace current ' in strings with \\'
    .replace(/'/g, "\\'")
    // Replace " (but not \") with '
    .replace(/(?<!\\)"/g, "'")
    // Replace \\" in strings with plain "
    .replace(/\\"/g, '"')
    // Add trailing commas to key: value pairs.
    .replace(/(^ +\w+: .+[^,]$)/gm, '$1,')
    // Add trailing closing of objects or Arrays.
    .replace(/(^ +[}\]]$)/gm, '$1,')

  fs.writeFile(
    'dist/graph-data.js',
    (
      '// File generated by relviz\n'
      + 'export const graphData = '
      + jsString
      + '\n'
    ),
    (err) => {
      if (err != null) {
        console.error(err)
      }
    },
  )
}

main()
  .then(
    () => {},
    (error) => {
      console.error(error)
    })
